name: Main Workflow

on:
  push:
    branches:
      - pipeline-refactor

jobs:
  main:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-zip-main.yml@pipeline-dispatcher-artifact-based
    secrets: inherit
    with:
      secret_name: "er-dispatcher-defaults-dev"
      environment: dev