name: Upload to GCS

on:
  push:
    branches:
        - pipeline
    # tags:
    #   - 'v*'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.vars.outputs.tag_name }}
    steps:
      - id: vars
        run: |
          echo "tag_name=er-dispatcher-src-${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: vars
    steps:
    - uses: actions/checkout@v3
    - name: Zip files
      run: |
        zip -r "${{ needs.vars.outputs.tag_name }}.zip" *
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifact-dev
        path: ${{ needs.vars.outputs.tag_name }}.zip
  
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: dev
    needs: [vars, build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact-dev
      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: Upload to Google Cloud Storage
        run: |
          gsutil cp "${{ needs.vars.outputs.tag_name }}.zip" gs://${{ vars.BUCKET }}/