name: Main Workflow

on:
  push:
    branches:
      - pipeline-refactor

jobs:
  main:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-zip-main.yml@main
    secrets: inherit
    with:
      secret_name: "er-dispatcher-defaults"
      environment: dev