name: Release Workflow

on:
  push:
    branches:
      - 'release-**'

jobs:
  release:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-zip-release.yml@pipeline-dispatcher-artifact-based
    secrets: inherit
    with:
      secret_name: "er-dispatcher-defaults"
      stage_environment: stage
      prod_environment: prod
      